// ===== BANKS DATA =====
const AZ_BANKS = [
    {
        id: "abbank",
        name: "ABB",
        fullName: "Azərbaycan Beynəlxalq Bankı",
        type: "az",
        logo: "🏦",
        color: "#003087",
        commission: "0.5%",
        minAmount: "10 AZN",
        maxAmount: "50,000 AZN",
        currencies: ["AZN", "USD", "EUR", "GBP", "RUB", "CHF"],
        workHours: "09:00 - 18:00",
        website: "https://abb-bank.az",
        features: ["Onlayn mübadilə", "Mobil bank", "24/7 ATM", "SWIFT köçürmə"],
        buySpread: 0.5,
        sellSpread: 0.5,
        description: "Azərbaycanın ən böyük dövlət bankı. Geniş filial şəbəkəsi."
    },
    {
        id: "kapital",
        name: "Kapital Bank",
        fullName: "Kapital Bank ASC",
        type: "az",
        logo: "💳",
        color: "#E30613",
        commission: "0.3%",
        minAmount: "5 AZN",
        maxAmount: "100,000 AZN",
        currencies: ["AZN", "USD", "EUR", "GBP", "RUB", "TRY", "CHF"],
        workHours: "09:00 - 19:00",
        website: "https://kapitalbank.az",
        features: ["Birbaşa mübadilə", "24/7 onlayn", "Sıfır komissiya (AZN/USD)", "Premium xidmət"],
        buySpread: 0.3,
        sellSpread: 0.4,
        description: "Azərbaycanın aparıcı özəl bankı. 700+ filial."
    },
    {
        id: "pasha",
        name: "PAŞA Bank",
        fullName: "PAŞA Bank ASC",
        type: "az",
        logo: "🏛️",
        color: "#1B2B5E",
        commission: "0.4%",
        minAmount: "50 AZN",
        maxAmount: "500,000 AZN",
        currencies: ["AZN", "USD", "EUR", "GBP", "CHF", "JPY"],
        workHours: "09:00 - 18:00",
        website: "https://pashabank.az",
        features: ["Korporativ xidmətlər", "SWIFT", "Valyuta müqaviləsi", "Premium"],
        buySpread: 0.4,
        sellSpread: 0.4,
        description: "Biznes və korporativ müştərilər üçün premium bank."
    },
    {
        id: "rabitabank",
        name: "RabитаBank",
        fullName: "RabитаBank ASC",
        type: "az",
        logo: "📡",
        color: "#007DC5",
        commission: "0.6%",
        minAmount: "10 AZN",
        maxAmount: "30,000 AZN",
        currencies: ["AZN", "USD", "EUR", "RUB"],
        workHours: "09:00 - 18:00",
        website: "https://rabitabank.com",
        features: ["Sadə prosedur", "Sürətli xidmət", "ATM şəbəkəsi"],
        buySpread: 0.6,
        sellSpread: 0.7,
        description: "Güvənilir rabitə infrastrukturlu bank."
    },
    {
        id: "atb",
        name: "Azər-Türk Bank",
        fullName: "Azər-Türk Bank ASC",
        type: "az",
        logo: "🤝",
        color: "#C8102E",
        commission: "0.35%",
        minAmount: "10 AZN",
        maxAmount: "200,000 AZN",
        currencies: ["AZN", "USD", "EUR", "TRY", "GBP"],
        workHours: "09:00 - 18:30",
        website: "https://atb.az",
        features: ["TRY mübadilə üstünlüyü", "Türkiyəyə köçürmə", "Rəqabətli kurs"],
        buySpread: 0.35,
        sellSpread: 0.35,
        description: "Azərbaycan-Türkiyə ortaqlığı. TRY üzrə ən yaxşı kurs."
    },
    {
        id: "expressbank",
        name: "Express Bank",
        fullName: "Express Bank ASC",
        type: "az",
        logo: "⚡",
        color: "#FF6B00",
        commission: "0.4%",
        minAmount: "5 AZN",
        maxAmount: "50,000 AZN",
        currencies: ["AZN", "USD", "EUR", "GBP", "RUB"],
        workHours: "08:00 - 20:00",
        website: "https://expressbank.az",
        features: ["Uzun iş saatı", "Sürətli xidmət", "Onlayn bank"],
        buySpread: 0.4,
        sellSpread: 0.5,
        description: "Sürətli və əlçatan bank xidmətləri."
    },
    {
        id: "unibank",
        name: "Unibank",
        fullName: "Unibank Kommersiya Bankı",
        type: "az",
        logo: "🔷",
        color: "#0052A5",
        commission: "0.45%",
        minAmount: "10 AZN",
        maxAmount: "75,000 AZN",
        currencies: ["AZN", "USD", "EUR", "RUB", "GBP"],
        workHours: "09:00 - 18:00",
        website: "https://unibank.az",
        features: ["Onlayn xidmət", "Geniş şəbəkə", "Sadiq müştəri bonusları"],
        buySpread: 0.45,
        sellSpread: 0.45,
        description: "Müştəri mərkəzli yanaşma ilə kommersiya bankı."
    },
    {
        id: "accessbank",
        name: "AccessBank",
        fullName: "AccessBank MMC",
        type: "az",
        logo: "🌐",
        color: "#00A651",
        commission: "0.55%",
        minAmount: "20 AZN",
        maxAmount: "25,000 AZN",
        currencies: ["AZN", "USD", "EUR"],
        workHours: "09:00 - 18:00",
        website: "https://accessbank.az",
        features: ["Mikro maliyyə", "Sadə prosedur", "KOB dəstəyi"],
        buySpread: 0.55,
        sellSpread: 0.6,
        description: "Kiçik biznes və fərdi müştərilər üçün."
    }
];

const INTL_BANKS = [
    {
        id: "wise",
        name: "Wise (TransferWise)",
        fullName: "Wise Payments Limited",
        type: "intl",
        logo: "🌍",
        color: "#00B9FF",
        commission: "0.35–0.7%",
        minAmount: "$1",
        maxAmount: "$1,000,000",
        currencies: ["USD", "EUR", "GBP", "AZN", "TRY", "RUB", "JPY", "AUD", "CAD", "+50"],
        workHours: "24/7 Onlayn",
        website: "https://wise.com",
        features: ["Orta bazar kursu", "Şəffaf komissiya", "Multi-valyuta hesab", "Debit kart"],
        buySpread: 0.35,
        sellSpread: 0.35,
        description: "Dünyanın ən şəffaf beynəlxalq köçürmə platformu."
    },
    {
        id: "revolut",
        name: "Revolut",
        fullName: "Revolut Ltd",
        type: "intl",
        logo: "💜",
        color: "#191C1F",
        commission: "0% (Planla)",
        minAmount: "£1",
        maxAmount: "Limitsiz",
        currencies: ["USD", "EUR", "GBP", "TRY", "AZN", "+30"],
        workHours: "24/7 Onlayn",
        website: "https://revolut.com",
        features: ["Ani köçürmə", "Kripto", "Birja", "Premium plan"],
        buySpread: 0.0,
        sellSpread: 0.5,
        description: "Fintech neobank. Gündəlik limitlər daxilində 0% komissiya."
    },
    {
        id: "paypal",
        name: "PayPal",
        fullName: "PayPal Holdings Inc.",
        type: "intl",
        logo: "💙",
        color: "#009CDE",
        commission: "3.5%",
        minAmount: "$0.01",
        maxAmount: "$10,000",
        currencies: ["USD", "EUR", "GBP", "+25"],
        workHours: "24/7 Onlayn",
        website: "https://paypal.com",
        features: ["Alıcı qoruması", "Geniş qəbul", "Ani ödəniş"],
        buySpread: 3.5,
        sellSpread: 3.5,
        description: "Dünyanın ən geniş yayılmış ödəniş sistemi."
    },
    {
        id: "swift",
        name: "SWIFT Köçürmə",
        fullName: "SWIFT Network (Bank Wire)",
        type: "intl",
        logo: "🏦",
        color: "#005B99",
        commission: "$15–$50 sabit",
        minAmount: "$100",
        maxAmount: "Limitsiz",
        currencies: ["Bütün valyutalar"],
        workHours: "İş günləri",
        website: "https://swift.com",
        features: ["Beynəlxalq bank köçürməsi", "Etibarlı", "Hər bankda"],
        buySpread: 0,
        sellSpread: 0,
        description: "Klassik beynəlxalq bank köçürmə sistemi. Yüksək etibarlılıq."
    }
];

// ===== CURRENCY DATA =====
const CURRENCY_INFO = {
    AZN: { name: "Azərbaycan Manatı", flag: "🇦🇿" },
    USD: { name: "ABŞ Dolları", flag: "🇺🇸" },
    EUR: { name: "Avro", flag: "🇪🇺" },
    GBP: { name: "Britaniya Funtu", flag: "🇬🇧" },
    RUB: { name: "Rusiya Rublu", flag: "🇷🇺" },
    TRY: { name: "Türk Lirəsi", flag: "🇹🇷" },
    CHF: { name: "İsveçrə Frankı", flag: "🇨🇭" },
    JPY: { name: "Yaponiya Yeni", flag: "🇯🇵" },
    CNY: { name: "Çin Yuanı", flag: "🇨🇳" },
    CAD: { name: "Kanada Dolları", flag: "🇨🇦" },
    AUD: { name: "Avstraliya Dolları", flag: "🇦🇺" },
    UAH: { name: "Ukrayna Qrivnası", flag: "🇺🇦" },
    KZT: { name: "Qazaxıstan Tengesi", flag: "🇰🇿" },
    GEL: { name: "Gürcüstan Larisi", flag: "🇬🇪" },
    SAR: { name: "Səudiyyə Riyalı", flag: "🇸🇦" },
    AED: { name: "BƏƏ Dirhəmi", flag: "🇦🇪" },
    INR: { name: "Hindistan Rupisi", flag: "🇮🇳" },
    BRL: { name: "Braziliya Realı", flag: "🇧🇷" },
    MXN: { name: "Meksika Pesosu", flag: "🇲🇽" },
    SEK: { name: "İsveç Kronası", flag: "🇸🇪" }
};

const AVAILABLE_CURRENCIES = ["AZN", "USD", "EUR", "GBP", "RUB", "TRY", "CHF", "JPY"];

// ===== TRANSFER FEE RULES =====
const TRANSFER_FEES = {
    AZN: { percent: 0.3, min: 0.30, max: 50, label: "0.3% (min 0.30 AZN, max 50 AZN)" },
    USD: { percent: 0.4, min: 0.50, max: 30, label: "0.4% (min $0.50, max $30)" },
    EUR: { percent: 0.4, min: 0.50, max: 30, label: "0.4% (min €0.50, max €30)" },
    GBP: { percent: 0.5, min: 0.50, max: 25, label: "0.5% (min £0.50, max £25)" },
    RUB: { percent: 0.5, min: 50,   max: 5000, label: "0.5% (min ₽50, max ₽5000)" },
    TRY: { percent: 0.4, min: 5,    max: 1000, label: "0.4% (min ₺5, max ₺1000)" }
};

function calcFee(amount, currency) {
    const rule = TRANSFER_FEES[currency] || { percent: 0.5, min: 0.5, max: 100 };
    const fee = Math.max(rule.min, Math.min(amount * rule.percent / 100, rule.max));
    return { fee: parseFloat(fee.toFixed(2)), rule };
}
